name: Run Colab Notebook

on:
  schedule:
    - cron: '0 0 * * *'  # Execute diariamente à meia-noite (ajuste conforme necessário)

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Colab Notebook
      run: |
        pip install colab-cli
        colab-cli login --username SEU_EMAIL --password SUA_SENHA
        colab-cli run --notebook Notebook.ipynb
